python run_experiment.py config/experiments/preflib/ED-24-1-unweighted.yml
python run_experiment.py config/experiments/preflib/ED-24-2-unweighted.yml
python run_experiment.py config/experiments/preflib/ED-24-3-unweighted.yml
python run_experiment.py config/experiments/preflib/ED-24-4-unweighted.yml
python run_experiment.py config/experiments/preflib/ED-25-1-unweighted.yml
python run_experiment.py config/experiments/preflib/ED-25-2-unweighted.yml
python run_experiment.py config/experiments/preflib/ED-25-3-unweighted.yml
python run_experiment.py config/experiments/preflib/ED-25-4-unweighted.yml
python run_experiment.py config/experiments/preflib/ED-32-2-unweighted.yml
python run_experiment.py config/experiments/preflib/ED-9-2-unweighted.yml
