python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_0.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_1.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_2.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_3.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_4.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_5.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_6.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_7.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_8.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_9.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_10.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_11.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_12.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_13.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_14.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_15.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_16.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_17.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_18.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_19.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_20.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_21.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_22.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_23.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_24.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_25.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_26.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_27.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_28.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_29.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_30.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_31.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_32.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_33.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_34.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_35.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_36.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_37.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_38.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_39.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_40.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_41.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_42.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_43.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_44.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_45.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_46.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_47.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_48.yml
python run_experiment.py config/experiments/random/exhaustive/rand_exp_4_50_49.yml
